---
title: "Activity 7"
---

# Exercise 1

Let's examine weather in 3 Australian locations.

```{r echo = FALSE}
# Load tidyverse package for plotting and wrangling
library(tidyverse)

# Import the data
weather <- read.csv("https://mac-stat.github.io/data/weather_3_locations.csv") |> 
  mutate(date = as.Date(date))
```

```{r}

ggplot(weather, aes(y = temp3pm, x = temp9am, color = location)) + 
  geom_point() + 
  labs(x = "temp9am", y = "temp3pm", title = "temp9am vs temp3pm by location", color = "Location")  
```
```{r}
ggplot(weather, aes(y = temp3pm, x = temp9am, color = location)) + 
  geom_point() + 
  labs(x= "temp9am", y = "temp3pm", color = "location")  
```
```{r}
ggplot(weather, aes(x = temp3pm, fill = location)) + 
  geom_density(alpha = 0.5) + 
  labs(x = "3pm temperature (Celsius)", alt = "density plot of 2pm temp by location") +
  scale_fill_viridis_d()    
```
```{r}
# In the color scale line:
# Change "fill" to "color" since we use color in the aes()
# Change "d" (discrete) to "c" (continuous) since maxtemp is on a continuous scale
ggplot(weather, aes(y = temp3pm, x = temp9am, color = maxtemp)) + 
  geom_point(alpha = 0.5) + 
  labs(x = "3pm temperature (Celsius)") + 
  scale_color_viridis_c()
```

